# -*- coding: utf-8 -*-
"""03_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwciDgOWa78MnIGpShLhagrq9a4imSgW

> Imports

---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from cleaning_01 import get_data, clean_data
from features_02 import run_phase2

"""> Load data from previous phases

---


"""

data = get_data()

cleaned_df, dup_count = clean_data(data)

df_features = run_phase2(cleaned_df)

df_features.head()

"""> Histograms / KDE

---

```
SalePrice is right-skewed, meaning most houses are lower priced with a few expensive ones.

Gr Liv Area is slightly right-skewed, so very large houses are less common.

Lot Area is highly skewed, with most lots being small.

```
"""

def plot_histograms_kde(df):

    cols = ["SalePrice", "Gr Liv Area", "Lot Area"]

    for col in cols:
        plt.figure(figsize = (6, 4))
        sns.histplot(df[col], kde = True, bins = 30)
        plt.title(f"{col} Distribution")
        plt.xlabel(col)
        plt.ylabel("Count")
        plt.show()

"""> Grouped boxplots

---

```
Higher kitchen quality leads to higher sale prices.

Newer houses tend to be more expensive than older ones
```
"""

def plot_grouped_boxplots(df):

    plt.figure(figsize = (7, 5))
    sns.boxplot(x = "Kitchen Qual Ord", y = "SalePrice", data = df)
    plt.title("SalePrice by Kitchen Quality")
    plt.xlabel("Kitchen Quality")
    plt.ylabel("SalePrice")
    plt.show()

    plt.figure(figsize = (7, 5))
    sns.boxplot(x = "Age Group", y = "SalePrice", data = df)
    plt.title("SalePrice by Age Group")
    plt.xlabel("Age Group")
    plt.ylabel("SalePrice")
    plt.show()

""">

> Correlation heatmap

---

```
Overall Qual and Gr Liv Area have the strongest correlation with SalePrice,
indicating that quality and size are key drivers of price.
```
"""

def plot_correlation_heatmap(df):

    top_corr = df.corr(numeric_only = True)["SalePrice"].abs().sort_values(ascending = False).head(10)

    top_features = top_corr.index

    plt.figure(figsize = (8, 6))
    sns.heatmap(df[top_features].corr(), annot = True, cmap = "coolwarm")
    plt.title("Top 10 Features Correlated with SalePrice")
    plt.show()

"""> Scatter plot

---

```
SalePrice increases as living area increases, and higher quality homes have higher prices.
```
"""

def plot_scatter(df):

    plt.figure(figsize = (7, 5))
    scatter = plt.scatter(
        df["Gr Liv Area"],
        df["SalePrice"],
        c = df["Overall Qual"],
        alpha = 0.6
    )

    plt.title("Gr Liv Area vs SalePrice by Overall Quality")
    plt.xlabel("Gr Liv Area")
    plt.ylabel("SalePrice")
    plt.colorbar(scatter, label = "Overall Quality")
    plt.show()

"""> Groupby summary

---

```
Newer houses have higher average prices than older ones.
```
"""

def groupby_summary(df):

    summary = df.groupby("Age Group")["SalePrice"].mean().sort_values()

    print(summary)

    print("\nHighest group:")
    print(summary.idxmax(), summary.max())

    print("\nLowest group:")
    print(summary.idxmin(), summary.min())

    return summary

"""> Run EDA

---


"""

def run_eda(df):

    plot_histograms_kde(df)

    plot_grouped_boxplots(df)

    plot_correlation_heatmap(df)

    plot_scatter(df)

    groupby_summary(df)

run_eda(df_features)