# -*- coding: utf-8 -*-
"""03_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwciDgOWa78MnIGpShLhagrq9a4imSgW

> Imports

---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from cleaning_01 import get_data, clean_data

"""> Load data from previous phases

---


"""

data = get_data()

cleaned_df, dup_count = clean_data(data)

cleaned_df.head()

"""> Histograms / KDE

---

```
The distributions show that SalePrice and Lot Area are right-skewed,
 meaning most houses are in the lower range with few high values.
```
"""

def plot_histograms(df):

    cols = ["SalePrice", "Gr Liv Area", "Lot Area"]

    for col in cols:
        plt.figure()
        sns.histplot(df[col], kde=True)
        plt.title(f"Distribution of {col}")
        plt.xlabel(col)
        plt.ylabel("Frequency")
        plt.show()

"""> Grouped boxplots

---

```
Higher kitchen and overall quality are associated with higher house prices.
```
"""

def plot_boxplots(df):

    plt.figure()
    sns.boxplot(x="Kitchen Qual", y="SalePrice", data=df)
    plt.title("SalePrice by Kitchen Quality")
    plt.show()

    plt.figure()
    sns.boxplot(x="Overall Qual", y="SalePrice", data=df)
    plt.title("SalePrice by Overall Quality")
    plt.show()

""">

> Correlation heatmap

---

```
Overall Qual and Gr Liv Area have the strongest correlation with SalePrice.
```
"""

def plot_correlation_heatmap(df):

    corr = df.corr(numeric_only=True)["SalePrice"].abs().sort_values(ascending=False).head(10)
    top_cols = corr.index

    plt.figure(figsize=(8,6))
    sns.heatmap(df[top_cols].corr(), annot=True, cmap="coolwarm")
    plt.title("Top Correlated Features with SalePrice")
    plt.show()

"""> Scatter plot

---

```
There is a positive relationship between living area and price, but it becomes weaker for very large houses.
```
"""

def plot_scatter(df):

    plt.figure()
    sns.scatterplot(x="Gr Liv Area", y="SalePrice", hue="Overall Qual", data=df)
    plt.title("Living Area vs SalePrice")
    plt.show()

"""> Groupby summary

---

```
Houses with higher overall quality have the highest average prices.
```
"""

def groupby_summary(df):

    summary = df.groupby("Overall Qual")["SalePrice"].mean()

    print(summary.sort_values())

    print("\nHighest:", summary.idxmax(), summary.max())
    print("Lowest:", summary.idxmin(), summary.min())

"""> Run EDA

---


"""

def run_eda(df):

    plot_histograms(df)
    plot_boxplots(df)
    plot_correlation_heatmap(df)
    plot_scatter(df)

run_eda(cleaned_df)