# -*- coding: utf-8 -*-
"""04_math.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2awPW2z3aKx2CtYUSkhTDc6u6HKVWbs

> Imports
---
"""

import numpy as np
from cleaning_01 import get_data, clean_data
from features_02 import run_phase2

data = get_data()
cleaned_df, _ = clean_data(data)
df_features = run_phase2(cleaned_df)

"""> Mean + Std

---

```
I computed mean and std manually.
```
"""

def compute_mean_std(df):

    x = df["SalePrice"].values

    mean = np.sum(x) / len(x)
    std = np.sqrt(np.sum((x - mean)**2) / len(x))

    print("Mean:", mean)
    print("Std:", std)

    return mean, std

"""> Standardization

---

```
I applied z-score manually
```
"""

def manual_standardization(df):

    x = df["Gr Liv Area"].values

    mean = np.mean(x)
    std = np.std(x)

    z = (x - mean) / std

    print("Manual mean:", np.mean(z))
    print("Manual std:", np.std(z))

    return z

"""> StandardScaler

---

```
I compared with StandardScaler.
```
"""

from sklearn.preprocessing import StandardScaler

def compare_scaler(df):

    scaler = StandardScaler()

    scaled = scaler.fit_transform(df[["Gr Liv Area"]])

    print("Scaler mean:", scaled.mean())
    print("Scaler std:", scaled.std())

"""> Cosine Similarity

---

```
I measured similarity between records.
```
"""

def cosine_similarity_calc(df):

    numeric_df = df.select_dtypes(include = np.number)

    high = numeric_df.loc[df["SalePrice"].idxmax()].values
    low = numeric_df.loc[df["SalePrice"].idxmin()].values

    cos_sim = np.dot(high, low) / (np.linalg.norm(high) * np.linalg.norm(low))

    print("Cosine similarity:", cos_sim)

    return cos_sim

"""> Probability

---

```
I estimated probability based on quality.
```
"""

def probability_calc(df):

    threshold = df["SalePrice"].quantile(0.75)

    high_quality = df[df["Overall Qual"] >= 7]

    prob = (high_quality["SalePrice"] > threshold).mean()

    print("Probability:", prob)

    return prob

"""> Run Math

---


"""

def run_math(df):

    compute_mean_std(df)
    manual_standardization(df)
    compare_scaler(df)
    cosine_similarity_calc(df)
    probability_calc(df)

run_math(df_features)