# -*- coding: utf-8 -*-
"""cleaning_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYYqNKvBgGTZXbGCQofW5G0NOXT6WSpy

> # Loading the Data

---
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import kagglehub
import os

def get_data():
    data = kagglehub.dataset_download("prevek18/ames-housing-dataset")
    return data

def load_data(data):
    csv_path = os.path.join(data, "AmesHousing.csv")
    df = pd.read_csv(csv_path)
    return df

def show_head(df):
  return df.head()

"""

> Checking the Shape


---

"""

def show_shape(df):
    return df.shape

"""> Inspecting Data Types

---


"""

def show_info(df):
    return df.info()

"""> Fixing Wrong Data Types

---


"""

def fix_data_types(df):
    df = df.copy()
    df["MS SubClass"] = df["MS SubClass"].astype(str)
    df["MS Zoning"] = df["MS Zoning"].astype(str).str.strip().str.lower()
    df["Neighborhood"] = df["Neighborhood"].astype(str).str.strip().str.lower()
    return df

"""> Finding Missing Values

---


"""

def show_missing(df, top = 15):
    miss = df.isnull().sum().sort_values(ascending = False).head(top)
    return miss

"""> Handling Missing Values

---


```
I used **fillna() instead of dropna() to keep as many rows as possible in the dataset.
```





"""

def handle_missing_values(df):
    df = df.copy()
    df["Lot Frontage"] = df["Lot Frontage"].fillna(df["Lot Frontage"].median())
    df["Alley"] = df["Alley"].fillna("Unknown")
    return df

"""> Handling Duplicates

```
I checked duplicate rows using df.duplicated().sum().

The result showed that there are no duplicate rows in the dataset, so no rows were removed.
```


---






"""

def check_duplicates(df):
    dup_count = df.duplicated().sum()
    return dup_count

"""Spotting Outliers

---


"""

def plot_boxplot(df):
    df["SalePrice"].plot.box()
    plt.title("Boxplot of SalePrice")
    plt.ylabel("SalePrice")
    plt.show()

"""> Capping Extreme Values at the 99th Percentile

---


"""

def handle_outliers(df):
    df = df.copy()
    upper_limit = df["SalePrice"].quantile(0.99)
    df["SalePrice"] = df["SalePrice"].clip(upper = upper_limit)
    return df

"""> Writing clean_data()

---


"""

def clean_data(data):

    df = load_data(data)

    df = fix_data_types(df)

    df = handle_missing_values(df)

    dup_count = check_duplicates(df)

    plot_boxplot(df)

    df = handle_outliers(df)

    return df, dup_count

"""> Running clean_data()

---


"""

def run_phase1():

    data = get_data()

    df = load_data(data)

    print("First rows:")
    print(show_head(df))

    print("\nShape:")
    print(show_shape(df))

    print("\nInfo:")
    show_info(df)

    print("\nMissing values before cleaning:")
    print(show_missing(df))

    cleaned_df, dup_count = clean_data(data)

    print("\nMissing values after cleaning:")
    print(show_missing(cleaned_df))

    print("\nDuplicates:", dup_count)

    print("\nFinal shape:")
    print(show_shape(cleaned_df))

    os.makedirs("data/cleaned", exist_ok = True)
    cleaned_df.to_csv("data/cleaned/ames_clean.csv", index = False)

    return cleaned_df

cleaned_df = run_phase1()

"""> Saving Cleaned CSV

---


"""

os.makedirs("data/cleaned", exist_ok = True)
cleaned_df.to_csv("data/cleaned/ames_clean.csv", index = False)

"""> Checks

---




"""

def run_checks(df):

    assert df["SalePrice"].isna().sum() == 0
    assert (df["SalePrice"] > 0).all()
    assert df.shape[1] == 82

    print("All checks passed successfully")

run_checks(cleaned_df)